BEGIN TRANSACTION

INSERT INTO Dipendenti VALUES('Neri',350);
SAVE TRANSACTION Punto1

SELECT * FROM Dipendenti

INSERT INTO Dipendenti VALUES('Viola',1800);
SAVE TRANSACTION Punto2

SELECT * FROM Dipendenti

ROLLBACK TRANSACTION Punto1

SELECT * FROM Dipendenti

COMMIT
